- name: "Install Curl"
  apt: name=curl state=present
  tags:
    - common

- name: "Install some apps"
  apt: name={{ item }} state=present
  with_items:
    - curl
    - wget
  tags:
    - common

- name: "Install Git"
  apt: name=git state=latest
  tags:
    - development
